conversions:
  "A+": 4.00
  "A": 3.67
  "A-": 3.33
  "B+": 3.00
  "B": 2.67
  "B-": 2.33
  "C+": 2.00
  "C": 1.67
  "C-": 1.33
  "D+": 1.00
  "D": 0.67 

scale:
  "AP": 1.00
  "H": 0.67
  "CP": 0.33
  "A": 0.00
  "E": 0.33
  "BASE": 0.33
